GET http://localhost:3001/tasks

###

POST http://localhost:3001/tasks
Content-Type: application/json

{
    "task": "HEOWIHERUIJKR"
}

### 
DELETE http://localhost:3001/tasks/62e4609661c793e631d426c2

###
PUT http://localhost:3001/tasks/62e5660c2852de00075c19fe
Content-Type: application/json

{
    "task": "HEOWIHERUIJKR"
}